name: Deploy React App to EC2 (No S3)

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/**'

jobs:
  deploy:
    name: Build and Deploy React to EC2 via SSM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Build React App
        run: |
          npm install --prefix src
          npm run build --prefix src
          cd src
          zip -r build.zip build
          base64 build.zip > ../build.b64

      - name: Get EC2 Instance ID
        id: ec2
        run: |
          INSTANCE_ID=$(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=react-app-server" \
            --query "Reservations[].Instances[].InstanceId" \
            --output text)
          echo "instance_id=$INSTANCE_ID" >> $GITHUB_OUTPUT
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Send React Build to EC2 via SSM
        run: |
          BASE64_CONTENT=$(cat build.b64)
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy React build directly via SSM" \
            --instance-ids "${{ steps.ec2.outputs.instance_id }}" \
            --parameters 'commands=[
              "echo \"'"$BASE64_CONTENT"'\" > /tmp/build.b64",
              "base64 -d /tmp/build.b64 > /tmp/build.zip",
              "sudo yum install -y unzip httpd",
              "sudo systemctl enable httpd && sudo systemctl start httpd",
              "sudo rm -rf /var/www/html/*",
              "sudo unzip -o /tmp/build.zip -d /var/www/html/"
            ]' \
            --region us-east-1 \
            --output text
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
