name: Terraform Deploy US-East-1

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Init & Apply
    runs-on: ubuntu-latest

    env:
      TF_VAR_file: terraform/tfvars/us-east-1.tfvars

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Parse region and bucket from tfvars
        id: parse
        run: |
          REGION=$(grep '^region' "$TF_VAR_file" | cut -d'=' -f2 | tr -d '" ')
          BUCKET=$(grep '^bucket_name' "$TF_VAR_file" | cut -d'=' -f2 | tr -d '" ')
          echo "region=$REGION" >> $GITHUB_OUTPUT
          echo "bucket=$BUCKET" >> $GITHUB_OUTPUT

      - name: Create backend S3 bucket if not exists
        run: |
          aws s3api head-bucket --bucket ${{ steps.parse.outputs.bucket }} 2>/dev/null || \
          aws s3api create-bucket \
            --bucket ${{ steps.parse.outputs.bucket }} \
            --region ${{ steps.parse.outputs.region }} \
            --create-bucket-configuration LocationConstraint=${{ steps.parse.outputs.region }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Generate backend config
        run: |
          echo "bucket = \"${{ steps.parse.outputs.bucket }}\"" > terraform/backend.hcl
          echo "key    = \"state/terraform.tfstate\"" >> terraform/backend.hcl
          echo "region = \"${{ steps.parse.outputs.region }}\"" >> terraform/backend.hcl

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init -backend-config=backend.hcl
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Apply
        run: terraform apply -var-file=tfvars/us-east-1.tfvars -auto-approve
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
