name: Deploy React App to EC2 via SSM

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/**'

jobs:
  deploy:
    name: Build and Deploy React App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check AWS CLI version
        run: aws --version

      - name: Parse bucket_name from tfvars
        id: tfvars
        run: |
          BUCKET=$(grep '^bucket_name' terraform/tfvars/us-east-1.tfvars | cut -d'=' -f2 | tr -d '" ')
          echo "bucket_name=$BUCKET" >> $GITHUB_OUTPUT

      - name: Build React App
        run: |
          npm install
          npm run build
          zip -r build.zip build

      - name: Upload React build.zip to S3 (same bucket as Terraform backend)
        run: |
          aws s3 cp build.zip s3://${{ steps.tfvars.outputs.bucket_name }}/react-app/build.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Get EC2 Instance ID
        id: ec2
        run: |
          INSTANCE_ID=$(aws ec2 describe-instances \
            --region us-east-1 \
            --filters "Name=tag:Name,Values=react-app-server" \
            --query "Reservations[].Instances[].InstanceId" \
            --output text)
          echo "instance_id=$INSTANCE_ID" >> $GITHUB_OUTPUT
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy React Build from S3 via SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy React app from S3" \
            --instance-ids "${{ steps.ec2.outputs.instance_id }}" \
            --parameters 'commands=[
              "sudo yum install -y unzip httpd",
              "sudo systemctl enable httpd && sudo systemctl start httpd",
              "sudo mkdir -p /var/www/html",
              "aws s3 cp s3://${{ steps.tfvars.outputs.bucket_name }}/react-app/build.zip /tmp/build.zip",
              "sudo unzip -o /tmp/build.zip -d /var/www/html"
            ]' \
            --region us-east-1 \
            --output text
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
