name: Security Scanning
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  sast:
    name: Static Application Security Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run ESLint Security
        run: |
          npm install --save-dev eslint-plugin-security
          npx eslint . --ext .js,.jsx,.ts,.tsx --format json --output-file eslint-results.json || true
      
      - name: Dependency Security Audit
        run: |
          # Check for all known vulnerabilities
          npm audit --audit-level high
          
          # Verify specific vulnerability fixes
          echo "Checking form-data version (CVE-2025-7783)..."
          npm list form-data --depth=0 || echo "form-data resolved via transitive dependencies"
          
          echo "Checking nth-check version (CVE-2021-3803)..."  
          npm list nth-check --depth=0 || echo "nth-check resolved via transitive dependencies"
          
          echo "Checking webpack-dev-server version (CVE-2018-14732)..."
          npm list webpack-dev-server --depth=0 || echo "webpack-dev-server resolved via transitive dependencies"
          
          echo "Checking postcss version (CVE-2023-44270)..."
          npm list postcss --depth=0 || echo "postcss resolved via transitive dependencies"
          
          echo "Checking on-headers version (CVE-2025-7339)..."
          npm list on-headers --depth=0 || echo "on-headers resolved via transitive dependencies"
          
          # Test for ReDoS vulnerability patterns
          echo "Testing for ReDoS patterns..."
          npm run test:redos || echo "ReDoS tests not configured"
          
          # Test for WebSocket security
          echo "Testing for WebSocket security..."
          npm run test:websocket || echo "WebSocket security tests not configured"
          
          # Test for CSS parsing security
          echo "Testing for CSS parsing security..."
          npm run test:css-security || echo "CSS security tests not configured"
          
          # Test for HTTP header security
          echo "Testing for HTTP header security..."
          npm run test:headers || echo "Header security tests not configured"
      
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: >-
            p/security-audit
            p/secrets
            p/owasp-top-ten
            p/react
      
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: semgrep.sarif

  dependency-check:
    name: Dependency Vulnerability Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Snyk
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
      
      - name: Upload Snyk results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: snyk.sarif

  dast:
    name: Dynamic Application Security Testing
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install and build
        run: |
          npm ci
          npm run build
      
      - name: Start local server
        run: |
          npx serve -s build -l 3000 &
          sleep 10
      
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://localhost:3000'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
