name: Terraform Lint
on:
  pull_request:
    paths:
      - 'terraform/**'
      - '.tflint.hcl'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Install tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      - name: Run tflint
        run: tflint --config .tflint.hcl terraform/
      - name: Run terraform fmt
        run: terraform fmt -check -recursive terraform/
